apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ai-task-platform
  labels:
    app.kubernetes.io/part-of: ai-task-platform
type: Opaque
stringData:
  JWT_SECRET: "CHANGE-ME-use-kubectl-or-sealed-secrets"
  MONGO_URI: "mongodb://mongodb-svc:27017/ai_task_platform"
  REDIS_URL: "redis://redis-svc:6379"
